### ISSUE TITLE
svglinkify.py doesn't seem to work if there are other rectangles with non-white fill in front of magenta rectangles 

### ISSUE THREAD

**Issue by botwhytho** [oxplot/gists#2]
I understand this is a big hack, but really appreciate you came up with this piece of code.

I don't know the internals of how Inkscape (using lib cairo?) converts SVGs to PDF but it seems like the technique you have to use for this to work only works for me if I have text that has a white rectangle behind it. Other areas I would want to create links in are in front of a rectangle with black background and others are in front of a rectangle with a semi-transparent pattern as a fill. 

Any insight into how this could be affecting the code and the workaround? I followed instructions to the tee regarding moving the rectangles around and grouping,etc. Also, the fact that I got some links to work, and all of them being on top of a white rectangle leads me to believe there is a connection with that.

I've looked at the code heavily and the main regex which grabs links from <a><rect> combinations doesn't seem like it would mind if there are other rectangles that don't match this pattern somewhere 'above' or 'below' the ones that do. Maybe move things to another layer?

I am willing to help debug this as the tool helped me out tremendously but would be even more useful if it doesn't have these current limitations.

**Comment by oxplot** [comment]
can you send me an example of a SVG that doesn't work?

**Comment by oxplot** [comment]
Idle for too long.
